#include "GetRes.hpp"
#include "Helper.hpp"
using namespace std;
using namespace sf;

Font GetRes::boldFont;
Font GetRes::gameFont;
Font GetRes::techFont;
Texture GetRes::explosionTex;
Texture GetRes::gameLogoTex;
Texture GetRes::menuBackTex;
Texture GetRes::creditsButtonTex;
Texture GetRes::exitButtonTex;
Texture GetRes::helpButtonTex;
Texture GetRes::playButtonTex;
Texture GetRes::enemyBulletTex;
Texture GetRes::enemyMissileTex;
Texture GetRes::enemyBodyTex1;
Texture GetRes::enemyBodyTex2;
Texture GetRes::enemyBodyTex3;
Texture GetRes::enemyBodyTex4;
Texture GetRes::enemyBodyTex5;
Texture GetRes::enemyBodyTex6;
Texture GetRes::enemyBodyTex7;
Texture GetRes::bossBodyTex;
Texture GetRes::playerBulletTex;
Texture GetRes::playerMissileTex;
Texture GetRes::playerBodyTex;
Texture GetRes::seaTex;
Texture GetRes::seaElem1;
Texture GetRes::seaElem2;
Texture GetRes::seaElem3;
Texture GetRes::seaElem4;
Texture GetRes::seaElem5;
Texture GetRes::landTex;
Texture GetRes::landElem1;
Texture GetRes::landElem2;
Texture GetRes::landElem3;
Texture GetRes::landElem4;
Texture GetRes::landElem5;
Texture GetRes::titleBar;
Texture GetRes::CompleteBody;
Texture GetRes::CompleteStar;
Texture GetRes::CompleteText;
Texture GetRes::CompleteButton;
Texture GetRes::failedStar;
Texture GetRes::failedText;
Texture GetRes::playAgain;
Texture GetRes::tryAgain;
Texture GetRes::closeButton;
Texture GetRes::missileCountTex;
Texture GetRes::retryCount;
Texture GetRes::cursor;
Texture GetRes::outMeter;
Texture GetRes::inMeter;
Texture GetRes::inMeterHover;
Texture GetRes::inMeterClick;
Texture GetRes::outMeterHand;
Texture GetRes::inMeterHand;
Texture GetRes::outMeterHint;

SoundBuffer GetRes::enemyBulletSound;
SoundBuffer GetRes::enemyMissileSound;
SoundBuffer GetRes::enemyExplodedSound;
SoundBuffer GetRes::enemyBulletExplosionSound;
SoundBuffer GetRes::enemyMissileExplosionSound;
SoundBuffer GetRes::playerBulletSound;
SoundBuffer GetRes::playerMissileSound;
SoundBuffer GetRes::playerExplodedSound;
SoundBuffer GetRes::playerBulletExplosionSound;
SoundBuffer GetRes::playerMissileExplosionSound;
SoundBuffer GetRes::playerFlySound;
SoundBuffer GetRes::failedMessageSound;
SoundBuffer GetRes::successMessageSound;
SoundBuffer GetRes::menuClickSound;
SoundBuffer GetRes::menuHoverSound;
SoundBuffer GetRes::typeWriterSound;
Texture GetRes::outMeterSuccess;
Texture GetRes::dummyButtons;

void GetRes::init()
{
	boldFont.loadFromFile("res/Roboto-Bold.ttf");
	gameFont.loadFromFile("res/Roboto-Regular.ttf");
	techFont.loadFromFile("res/AgencyFB-Regular.ttf");
	explosionTex.loadFromFile("res/explosion.png");
	gameLogoTex.loadFromFile("res/game_logo.png");
	menuBackTex.loadFromFile("res/menu_background.jpg");
	creditsButtonTex.loadFromFile("res/credits_button.png");
	exitButtonTex.loadFromFile("res/exit_button.png");
	helpButtonTex.loadFromFile("res/help_button.png");
	playButtonTex.loadFromFile("res/play_button.png");
	enemyBulletTex.loadFromFile("res/enemy_bullet.png");
	enemyMissileTex.loadFromFile("res/enemy_missile.png");
	enemyBodyTex1.loadFromFile("res/enemy1_spritesheet.png");
	enemyBodyTex2.loadFromFile("res/enemy2_spritesheet.png");
	enemyBodyTex3.loadFromFile("res/enemy3_spritesheet.png");
	enemyBodyTex4.loadFromFile("res/enemy4_spritesheet.png");
	enemyBodyTex5.loadFromFile("res/enemy5_spritesheet.png");
	enemyBodyTex6.loadFromFile("res/enemy6_spritesheet.png");
	enemyBodyTex7.loadFromFile("res/enemy7_spritesheet.png");
	bossBodyTex.loadFromFile("res/boss_spritesheet.png");
	playerBulletTex.loadFromFile("res/player_bullet.png");
	playerMissileTex.loadFromFile("res/player_missile.png");
	playerBodyTex.loadFromFile("res/player_spritesheet.png");
	seaTex.loadFromFile("res/sea_texture.png");
	seaElem1.loadFromFile("res/sea_elem1.png");
	seaElem2.loadFromFile("res/sea_elem2.png");
	seaElem3.loadFromFile("res/sea_elem3.png");
	seaElem4.loadFromFile("res/sea_elem4.png");
	seaElem5.loadFromFile("res/sea_elem5.png");
	landTex.loadFromFile("res/land_texture.png");
	landElem1.loadFromFile("res/land_elem1.png");
	landElem2.loadFromFile("res/land_elem2.png");
	landElem3.loadFromFile("res/land_elem3.png");
	landElem4.loadFromFile("res/land_elem4.png");
	landElem5.loadFromFile("res/land_elem5.png");
	titleBar.loadFromFile("res/title_bar.png");
	CompleteBody.loadFromFile("res/objective_completed_body.png");
	CompleteStar.loadFromFile("res/objective_completed_star.png");
	CompleteText.loadFromFile("res/objective_completed_text.png");
	CompleteButton.loadFromFile("res/proceed_spritesheet.png");
	failedStar.loadFromFile("res/failed_star.png");
	failedText.loadFromFile("res/failed.png");
	playAgain.loadFromFile("res/play_again.png");
	tryAgain.loadFromFile("res/try_again.png");
	closeButton.loadFromFile("res/close.png");
	missileCountTex.loadFromFile("res/missile_texture.png");
	retryCount.loadFromFile("res/retry_texture.png");
	cursor.loadFromFile("res/cursor_spritesheet.png");
	outMeter.loadFromFile("res/output.png");
	inMeter.loadFromFile("res/input.png");
	inMeterHover.loadFromFile("res/input_hover.png");
	inMeterClick.loadFromFile("res/input_click.png");
	outMeterHand.loadFromFile("res/output_hand.png");
	inMeterHand.loadFromFile("res/input_hand.png");
	outMeterHint.loadFromFile("res/output_hint.png");
	outMeterSuccess.loadFromFile("res/output_complete.png");
	dummyButtons.loadFromFile("res/dummy_button.png");

	enemyBulletSound.loadFromFile("res/music/enemy_bullet.wav");
	enemyMissileSound.loadFromFile("res/music/enemy_missile.wav");
	enemyExplodedSound.loadFromFile("res/music/enemy_exploded.wav");
	enemyBulletExplosionSound.loadFromFile("res/music/enemy_explosion_bullet.ogg");
	enemyMissileExplosionSound.loadFromFile("res/music/enemy_explosion_missile.wav");
	playerBulletSound.loadFromFile("res/music/player_bullet.ogg");
	playerMissileSound.loadFromFile("res/music/player_missile.wav");
	playerExplodedSound.loadFromFile("res/music/player_exploded.wav");
	playerBulletExplosionSound.loadFromFile("res/music/player_explosion_bullet.wav");
	playerMissileExplosionSound.loadFromFile("res/music/player_explosion_missile.wav");
	playerFlySound.loadFromFile("res/music/player_flyaway.wav");
	failedMessageSound.loadFromFile("res/music/failed.wav");
	successMessageSound.loadFromFile("res/music/success.ogg");
	menuClickSound.loadFromFile("res/music/menu_clicked.wav");
	menuHoverSound.loadFromFile("res/music/menu_hover.wav");
	typeWriterSound.loadFromFile("res/music/typewriter.ogg");

	explosionTex.setSmooth(true);
	outMeterSuccess.setSmooth(true);
	gameLogoTex.setSmooth(true);
	menuBackTex.setSmooth(true);
	creditsButtonTex.setSmooth(true);
	exitButtonTex.setSmooth(true);
	helpButtonTex.setSmooth(true);
	playButtonTex.setSmooth(true);
	enemyBulletTex.setSmooth(true);
	enemyMissileTex.setSmooth(true);
	enemyBodyTex1.setSmooth(true);
	enemyBodyTex2.setSmooth(true);
	enemyBodyTex3.setSmooth(true);
	enemyBodyTex4.setSmooth(true);
	enemyBodyTex5.setSmooth(true);
	enemyBodyTex6.setSmooth(true);
	enemyBodyTex7.setSmooth(true);
	bossBodyTex.setSmooth(true);
	dummyButtons.setSmooth(true);
	playerBulletTex.setSmooth(true);
	playerMissileTex.setSmooth(true);
	playerBodyTex.setSmooth(true);
	// seaTex.setSmooth(true);
	seaElem1.setSmooth(true);
	seaElem2.setSmooth(true);
	seaElem3.setSmooth(true);
	seaElem4.setSmooth(true);
	seaElem5.setSmooth(true);
	// landTex.setSmooth(true);
	landElem1.setSmooth(true);
	landElem2.setSmooth(true);
	landElem3.setSmooth(true);
	landElem4.setSmooth(true);
	landElem5.setSmooth(true);
	titleBar.setSmooth(true);
	CompleteBody.setSmooth(true);
	CompleteStar.setSmooth(true);
	CompleteText.setSmooth(true);
	CompleteButton.setSmooth(true);
	failedStar.setSmooth(true);
	failedText.setSmooth(true);
	playAgain.setSmooth(true);
	tryAgain.setSmooth(true);
	closeButton.setSmooth(true);
	missileCountTex.setSmooth(true);
	retryCount.setSmooth(true);
	cursor.setSmooth(true);
	outMeter.setSmooth(true);
	inMeter.setSmooth(true);
	inMeterHover.setSmooth(true);
	inMeterClick.setSmooth(true);
	outMeterHand.setSmooth(true);
	inMeterHand.setSmooth(true);
	outMeterHint.setSmooth(true);
}